#!/usr/bin/env python
Import('env')

module_env = env.Clone()

module_env.add_source_files(env.modules_sources, '*.cpp')
module_env.add_source_files(env.modules_sources, 'plugins/*.cpp')

if env['target'] == 'release':
    module_env.Append(CPPFLAGS=['-std=c++11', '-O3'])
else:  # release_debug, debug
    module_env.Append(CPPFLAGS=['-std=c++11'])

for key, value in ARGLIST:
    if key == 'define':
        module_env.Append(CPPDEFINES=[value])

Export('module_env')
