#!/usr/bin/env python
Import('env')
Import('env_modules')

module_env = env_modules.Clone()

module_env.add_source_files(env.modules_sources, '*.cpp')
module_env.add_source_files(env.modules_sources, 'plugins/*.cpp')

module_env.Append(CPPFLAGS=['-std=c++11'])
